name: CI

on: [push]

jobs:
  macos_intel_operational_test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - run: brew install ./hb.rb
    - run: hb --version
    - run: hb --help

  linux_amd64_operational_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # "brew: command not found" occurred without the following
    - name: Install brew
      run: |
        set -eu
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
    - run: brew install ./hb.rb
    - run: hb --version
    - run: hb --help
